### PR TITLE
Add Python to Editor UI

### PR DESCRIPTION
**Pull request by swatkins**

### CODE REVIEW

**Comment by jsoutherland** [comment]
@swatkins Thanks for merging that work in.

**Comment by jsoutherland** [comment]
@swatkins on a linux VM, I was able to test python program execution after commenting out 
````python
import wallaby
````
after creating a python project,

**Comment by jsoutherland** [comment]
@swatkins  Thanks!

**Comment by swatkins** [comment]
@jsoutherland do we need to remove that line (`import wallaby`) from the Python template?

**Comment by jsoutherland** [comment]
@swatkins that line is needed when interacting with the motors/servos/etc. It will work on the wallaby, we just didn't have the wallaby lib built on our test machines.

**Pull request merged**
